import Head from 'next/head';
import Layout from '../components/Layout/Layout';
import { useMail } from '../hooks/useMail';
import Style from './css/contact.module.css';

const Contact: React.FC = () => {
    const { setName, setEmail, setMessage, send, pending } = useMail();

    return (
        <>
            <Head>
                <title>Create Next App | CONTACT</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Layout>
                <main className="contact">
                    <section className={ Style.contact }>
                        <div className={ Style.form }>
                            <dl>
                                <dt>お名前</dt>
                                <dd><input type="text" className={ Style.input } onChange={(e) => setName(e.target.value)} /></dd>
                            </dl>
                            <dl>
                                <dt>メールアドレス</dt>
                                <dd><input type="email" className={ Style.input } onChange={(e) => setEmail(e.target.value)} /></dd>
                            </dl>
                            <dl className={ Style.lastForm }>
                                <dt>問い合わせ内容</dt>
                                <dd><textarea className={ Style.input } onChange={(e) => setMessage(e.target.value)} /></dd>
                            </dl>
                            {pending && <p className={ Style.pending }>メール送信中...</p>}
                            <button type="submit" className={ Style.submit } onClick={send}>内容を送信する</button>
                        </div>
                    </section>
                </main>
            </Layout>
        </>
    );
}

export default Contact;