import Head from 'next/head';
// import Image from 'next/image';
import Layout from '../components/Layout/Layout';

const Index: React.FC = () => {
  return (
    <>
      <Head>
        <title>Create Next App | HOME</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
          <main className="top">
          <h2>Top</h2>
          </main>
      </Layout>
    </>
  )
}

export default Index;